version: "3"
services:
  reverseproxy:
      image: reverseproxy
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend-user
        - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: udagramhatemdev
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: udagramhatemdev 
      POSTGRES_HOST: udagramhatemdev.cku43frwooce.us-east-2.rds.amazonaws.com
      AWS_REGION: us-east-2
      AWS_PROFILE: DEPLOYED
      AWS_BUCKET: udagram-east-hatem-bucket
      JWT_SECRET: helloWorld
      URL: "http://localhost:8100"
      # POSTGRES_USERNAME: $POSTGRES_USERNAME
      # POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      # POSTGRES_DB: $POSTGRES_DB 
      # POSTGRES_HOST: $POSTGRES_HOST
      # AWS_REGION: $AWS_REGION 
      # AWS_PROFILE: $AWS_PROFILE 
      # AWS_BUCKET: $AWS_BUCKET
      # JWT_SECRET: $JWT_SECRET
      # URL: "http://localhost:8100"
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"
  frontend:
    image: udagram-frontend:local
    ports:
      - "8100:80"
